### ISSUE TITLE
Gem with same name

### ISSUE THREAD

**Issue by fabioxgn** [dropstream/omniauth-amazon#1]
Hi @ests I noticed that there is already another gem called `omniauth-amazon`: https://github.com/wingrunr21/omniauth-amazon are you using your gem in production? Do you plan to publish it to Rubygems? Maybe rename this one to `omniauth-amazon-sp-api` to be easier to find on Google?

I need to do OAuth with the Amazon SP API and would like to use your gem, and of course, contribute to it if there's something I can help with.

**Comment by nina-saule** [comment]
Hi @fabioxgn, thank your for your message.
I agree that gem name if unfortunate, because it is for SP API only. I think the renaming to `omniauth-amazon-sp-api` should be possible, I just need to check few things.
Currently the gem is used for some beta features. After rename maybe we could release it to Rubygems. I am open for any ideas of improvement, for starters it needs better readme, and (maybe) few additional tests.
Let me know if I can help in any way.

**Comment by nina-saule** [comment]
I plan to archive this repo. Please see 

https://github.com/dropstream/omniauth-amazon-ap-api
